### ISSUE TITLE
Support for linuxArm32Hfp - Raspberry Pi?

### ISSUE THREAD

**Issue by v79** [korlibs/korlibs-all#12]
Have you considered supporting the Raspberry Pi with a linuxArm32Hfp target? I've had some success just duplicating the linuxX64 code on other projects when trying to support the Pi.

**Comment by soywiz** [comment]
Considered it. The problem is that I could support new targets as they arise: That includes variants like x86/x64, arm, mips, risc-v, 32-bit, 64-bit, litle-big endian, hard/soft floats variants etc. that would increase the already long time it takes to build stuff on CI, along artifact sizes.

I hope at some point, Kotlin/Native will support compiling to something portable that supports compiling once and supporting all the targets as long as there is a compiler for the target platform.

In the meantime your best bet, is to use https://github.com/korlibs/korge-next to compile all the libraries at once for your wanted platform, ie. raspbery pi / linuxArm32Hfp, then publish the artifacts to maven local and use them there. I know this solution is not perfect, but hope you understand my rationale.

If at some point Kotlin/Native compilation approach, or compilation times reduce drastically, I could consider it again.

In any case, thanks for your suggestion!
